config/routes.rb
DesksnearMe::Application.routes.draw do

  if defined? MailView
    mount ReservationMailerPreview => 'mail_view/reservations'
    mount UserMailerPreview => 'mail_view/users'
    mount PostActionMailerPreview => 'mail_view/post_action'
    mount InquiryMailerPreview => 'mail_view/inquiries'
    mount ListingMailerPreview => 'mail_view/listings'
    mount RatingMailerPreview => 'mail_view/ratings'
    mount ListingMessagingMailerPreview => 'mail_view/listing_messaging'
    mount ReengagementMailerPreview => 'mail_view/reengagement'
    mount RecurringMailerPreview => 'mail_view/recurring'
  end

  match '/404', :to => 'errors#not_found'
  match '/422', :to => 'errors#server_error'
  match '/500', :to => 'errors#server_error'
  match '/domain-not-configured', :to => 'errors#domain_not_configured', :as => 'domain_not_configured'

  namespace :admin do
    match '/', :to => "dashboard#show"
    resources :users do
      member do
        post :login_as
      end

      collection do
        post :restore_session
      end
    end

    resources :reservations
    resources :companies
    resources :payment_transfers do
      member do
        post :transferred
      end

      collection do
        post :generate
      end
    end

    resources :instances do
      resources :partners
    end
    resources :pages
  end

  namespace :instance_admin do
    match '/', :to => "base#index"
    resources :analytics, :only => [:index]
    resources :inventories, :only => [:index, :show] do
      post :login_as, on: :member
      post :restore_session, on: :collection
    end
    resources :partners
    resources :settings, :only => [:index]
    resource :theme, :only => [:show, :update], :controller => 'theme'
    resources :transfers do
      member do
        post :transferred
      end

      collection do
        post :generate
      end
    end
    resources :users, :only => [:index, :create]
    resources :pages

    namespace :users do
      resources :instance_admins, :only => [:create, :update, :destroy, :index]
      resources :instance_admin_roles, :only => [:create, :update, :destroy, :index]
    end
  end

  resources :locations, :only => [:show] do
    resources :listings, :controller => 'locations/listings' do
      member do
        get :ask_a_question
      end
    end

    resource :social_share, :only => [:new], :controller => 'locations/social_share'

    collection do
      get :populate_address_components_form
      post :populate_address_components
    end
  end

  resources :listings, :only => [:index, :show] do
    resources :reservations, :only => [:create, :update], :controller => "listings/reservations" do
      collection do
        post :review
        post :store_reservation_request
      end
      member do
        get :booking_successful
      end
      get :hourly_availability_schedule, :on => :collection
    end

    resources :listing_messages, :controller => "listings/listing_messages" do
      put :archive
    end
  end

  resources :listing_messages, only: [:index] do 
    collection do 
      get :archived
    end
  end

  resources :reservations, :only => [] do
    resources :guest_ratings, :only => [:new, :create]
    resources :host_ratings, :only => [:new, :create]
  end
  match '/reservations/:id/guest_rating' => 'dashboard#guest_rating', as: 'guest_rating'
  match '/reservations/:id/host_rating' => 'reservations#host_rating', as: 'host_rating'

  match '/auth/:provider/callback' => 'authentications#create'
  match "/auth/failure", to: "authentications#failure"
  devise_for :users, :controllers => { :registrations => 'registrations', :sessions => 'sessions', :passwords => 'passwords' }
  devise_scope :user do
    post "users/avatar", :to => "registrations#avatar", :as => "avatar"
    get "users/edit_avatar", :to => "registrations#edit_avatar", :as => "edit_avatar"
    put "users/update_avatar", :to => "registrations#update_avatar", :as => "update_avatar"
    get "users/set_password", :to => "registrations#set_password", :as => "set_password"
    put "users/update_password", :to => "registrations#update_password", :as => "update_password"
    post "users/store_google_analytics_id", :to => "registrations#store_google_analytics_id", :as => "store_google_analytics"
    post "users/store_geolocated_location", :to => "registrations#store_geolocated_location", :as => "store_geolocated_location"
    get "users/", :to => "registrations#new"
    get "users/verify/:id/:token", :to => "registrations#verify", :as => "verify_user"
    delete "users/avatar", :to => "registrations#destroy_avatar", :as => "destroy_avatar"
    get "users/:id", :to => "registrations#show", :as => "profile"
    get "users/unsubscribe/:signature", :to => "registrations#unsubscribe", :as => "unsubscribe"

    put "users/store_correct_ip", :to => "sessions#store_correct_ip", :as => "store_correct_ip"
  end

  resources :reservations, :except => [:update, :destroy, :show] do
    member do
      post :user_cancel
      get :export
      get :booking_successful
    end
    collection do
      get :upcoming
      get :archived
    end
  end

  resource :dashboard, :only => [:show], :controller => 'dashboard' do
    member do
      get :bookings, :to => 'reservations#upcoming'
      get :analytics
      get :listings
      get :manage_guests
      get :transfers
    end
  end

  namespace :manage do

    resources :companies, :only => [:edit, :update, :show]

    resources :white_labels, :only => [:edit, :update, :show]

    resources :users, :except => [:edit, :update]
    resources :themes, :only => [] do
      member do
        delete :destroy_image
      end
    end

    resources :locations do
      resources :listings do
        member do
          get :enable
          get :disable
        end
      end
    end

    resources :photos, :only => [:create, :destroy, :edit, :update]

    resources :listings do
      resources :reservations, :controller => 'listings/reservations' do
        member do
          post :confirm
          get :confirm
          put :reject
          get :rejection_form
          post :host_cancel
        end
      end
    end
  end

  match "/search", :to => "search#index", :as => :search
  match "/search/show/:id", :to => "search#show"

  resources :search_notifications, only: [:create]

  resource :event_tracker, only: [:create], :controller => 'event_tracker'

  resources :authentications, :only => [:create, :destroy] do
    collection do
      post :clear # Clear authentications stored in session
    end
  end

  scope '/space' do
    get '/new' => 'space_wizard#new', :as => "new_space_wizard"
    get "/list" => "space_wizard#list", :as => "space_wizard_list"
    post "/list" => "space_wizard#submit_listing"
    put "/list" => "space_wizard#submit_listing"
    post "/photo" => "space_wizard#submit_photo", :as => "space_wizard_photo"
    put "/photo" => "space_wizard#submit_photo", :as => "space_wizard_photo"
    delete "/photo/:id" => "space_wizard#destroy_photo", :as => "destroy_space_wizard_photo"
  end

  root :to => "public#index"

  namespace :v1, :defaults => { :format => 'json' } do

    resource :authentication, only: [:create]
    post 'authentication/:provider', :to => 'authentications#social'

    resource :registration, only: [:create]

    get  'profile',  :to => 'profile#show'
    put  'profile',  :to => 'profile#update'
    post 'profile/avatar/:filename', :to => 'profile#upload_avatar'
    delete 'profile/avatar', :to => 'profile#destroy_avatar'

    get  'iplookup',  :to => 'iplookup#index'

    resources :guest_ratings, :only => [:create]
    resources :host_ratings, :only => [:create]

    resources :locations do
      collection do
        get 'list'
      end
    end

    resources :photos

    resources :listings, :only => [:show,:create, :update, :destroy] do
      member do
        post 'reservation'
        post 'availability'
        post 'inquiry'
        post 'share'
        get  'patrons'
        get  'connections'
      end
      collection do
        post 'search'
        post 'query'
      end
      resource :rating, only: [:show, :update, :destroy]
    end

    resources :reservations do
      collection do
        get 'past'
        get 'future'
      end
    end

    resource :social, only: [:show], controller: 'social' do
      # Hmm, can this be better?
      resource :facebook, only: [:show, :update, :destroy],
        controller: 'social_provider', provider: 'facebook'
      resource :twitter,  only: [:show, :update, :destroy],
        controller: 'social_provider', provider: 'twitter'
      resource :linkedin, only: [:show, :update, :destroy],
        controller: 'social_provider', provider: 'linkedin'
    end

    get 'amenities', to: 'amenities#index'
    get 'organizations', to: 'organizations#index'
  end

  match "/pages/:path", to: 'pages#show', as: :pages
  match "/w-hotels-desks-near-me", to: 'locations#w_hotels', as: :w_hotels_location
  match "/W-hotels-desks-near-me", to: 'locations#w_hotels'
  match "/careers", to: 'pages#careers'
  match "/rent-accounting-desks", to: 'locations#vertical_accounting'
  match "/rent-legal-desks", to: 'locations#vertical_law'
  match "/rent-hairdressing-booth-stations", to: redirect(subdomain: 'rent-salon-space', path: '/')
  match "/rent-design-desks", to: 'locations#vertical_design'
end

app/models/listing/search/area.rb
class Listing::Search::Area < Struct.new(:center, :bounds, :radius, :address_components)
  delegate :distance_from, :radians, to: :center

  def fetch_address_component(name)
    address_components.fetch_address_component(name)
  end
end

app/models/listing/search/errors.rb
module Listing::Search::Errors
  class Listing::Search::SearchTypeNotSupported < StandardError 
  end
end

app/models/listing/search/geocoder.rb
class Listing::Search::Geocoder

  def self.find_search_area(query)
    geocoded = ::Geocoder.search(query).try(:first)
    return nil if geocoded.nil?

    geo = geocoded.data['geometry']
    center = [geo['location']['lat'], geo['location']['lng']]

    bounds = if b = geo['viewport'] || geo['bounds']
      [b['northeast'].values, b['southwest'].values]
    else
      radius = geo['location_type'] == 'ROOFTOP' ? Listing::Search::Params::MIN_SEARCH_RADIUS : Listing::Search::Params::DEFAULT_SEARCH_RADIUS
      box = ::Geocoder::Calculations.bounding_box([center.lat, center.long], radius)
      [box[0..1], box[2..3]]
    end

    radius ||= ::Geocoder::Calculations.distance_between(*bounds)

    return Listing::Search::Area.new(center, bounds, radius, address_components(geocoded))
  end

  def self.address_components(geocoded)
    address_components = geocoded.data['address_components']

    populator = Location::AddressComponentsPopulator.new
    populator.set_result(geocoded)
    wrapped_address_components = populator.wrap_result_address_components

    Location::GoogleGeolocationDataParser.new(wrapped_address_components)
  end

end

app/models/listing/search/params.rb
require 'active_support/core_ext'

class Listing::Search::Params
  DEFAULT_SEARCH_RADIUS = 150.0 # in miles
  MIN_SEARCH_RADIUS = 7.0 # in miles

  attr_accessor :geocoder
  attr_reader :availability, :price, :amenities, :options, :search_area, :midpoint, :bounding_box, :location

  def initialize(options)
    @geocoder = Listing::Search::Geocoder
    @options = options.respond_to?(:deep_symbolize_keys) ? options.deep_symbolize_keys : options.symbolize_keys

    if !midpoint && query.present?
      @location = @geocoder.find_search_area(query)
      if @location.present?
        @bounding_box, @midpoint, @radius = @location.bounds, @location.center, @location.radius
      end
    end

    @availability = if @options[:availability].present?
      Availability.new(@options[:availability])
    else
      NullAvailability.new
    end

    @amenities = [*@options[:amenities]].map(&:to_i)

    @price = if @options[:price].present?
      PriceRange.new(@options[:price][:min], @options[:price][:max])
    else
      NullPriceRange.new
    end
  end

  def query
    @options[:query] || @options[:q] || @options[:address]
  end

  def radius
    @radius ||= begin
      if bounding_box.present?
        ::Geocoder::Calculations.distance_between(*bounding_box) / 2
      else
        Listing::Search::Params::DEFAULT_SEARCH_RADIUS
      end
    end

    @radius > MIN_SEARCH_RADIUS ? @radius : MIN_SEARCH_RADIUS
  end

  def midpoint
    @midpoint ||= begin
      if @options[:location].present?
        [@options[:location][:lat], @options[:location][:lon]]
      elsif bounding_box.present?
        ::Geocoder::Calculations.geographic_center(bounding_box)
      end
    end
  end

  def bounding_box
    @bounding_box ||= begin
      if @options[:boundingbox].present?
        box = @options[:boundingbox]
        [[box[:start][:lat], box[:start][:lon]], [box[:end][:lat], box[:end][:lon]]]
      end
    end
  end

  def available_dates
    availability.dates
  end

end

app/models/listing/search/params/null_availability.rb
class Listing::Search::Params::NullAvailability
  def min
    1
  end

  def dates
    []
  end
end

app/controllers/search_controller.rb
require "will_paginate/array"
class SearchController < ApplicationController

  helper_method :search, :query, :listings, :result_view, :search_notification

  SEARCH_RESULT_VIEWS = %w(list map)

  def index
    @located = (params[:lat].present? and params[:lng].present?)
    render "search/#{result_view}"
    if should_log_conducted_search?
      event_tracker.conducted_a_search(search, { search_query: query, result_view: result_view, result_count: result_count}.merge(filters))
    end

    event_tracker.track_event_within_email(current_user, request) if params[:track_email_event]

    remember_search_query
  end

  def show
    @listings = Listing.find(params[:id].split(','))
    render partial: "search/#{result_view}/listing", collection: listings, as: :listing
  end

  private

  def search
    @search ||= Listing::Search::Params::Web.new(params)
  end

  def query
    @query ||= search.query
  end

  def filters
    search_filters = {}
    search_filters[:listing_type_filter] = params[:listing_types_ids].map { |lt| ListingType.find(lt).name } if params[:listing_types_ids]
    search_filters[:location_type_filter] = params[:location_types_ids].map { |lt| LocationType.find(lt).name } if params[:location_types_ids]
    search_filters[:industry_filter] = params[:industries_ids].map { |i| Industry.find(i).name } if params[:industries_ids]
    search_filters
  end

  def listings
    @listings ||=  get_listings
  end

  def get_listings
    params_object = Listing::Search::Params::Web.new(params)
    search_params = params.merge({:midpoint => params_object.midpoint, :radius => params_object.radius, :available_dates => params_object.available_dates})
    collection = Listing::SearchFetcher.new(search_scope, search_params).listings
    params[:page] ||= 1
    if result_view == 'list'
      collection = WillPaginate::Collection.create(params[:page], 20, collection.count) do |pager|
        pager.replace(collection[pager.offset, pager.per_page].to_a)
      end
    end
    collection
  end

  def result_view
    requested_view = params.fetch(:v, 'list').downcase
    @result_view ||= if SEARCH_RESULT_VIEWS.include?(requested_view)
      requested_view
    else
      'list'
    end
  end

  def result_count
    if result_view == 'list'
      @listings.total_entries
    else
      @listings.size
    end
  end

  def should_log_conducted_search?
    first_result_page? && ignore_search_event_flag_false? && !repeated_search? && params[:q]
  end

  def first_result_page?
    !params[:page] || params[:page].to_i==1
  end

  def ignore_search_event_flag_false?
    params[:ignore_search_event].nil? || params[:ignore_search_event].to_i.zero?
  end

  def remember_search_query
    if params[:q]
      cookies[:last_search_query] = {
        :value => search_query_values,
        :expires => (Time.zone.now + 1.hour),
      }
    end
  end

  def search_query_values
    { 
      :q => params[:q],
      :listing_types_ids => params[:listing_types_ids],
      :location_types_ids => params[:location_types_ids],
      :industries_ids => params[:industries_ids]
    }

  end

  def repeated_search?
    params[:q] && search_query_values.to_s == cookies[:last_search_query].try(:to_s)
  end

  def search_notification
    @search_notification ||= SearchNotification.new(query: params[:q], latitude: params[:lat], longitude: params[:lng])
  end
end

app/helpers/search_helper.rb
module SearchHelper
  # Special geolocation fields for the search form(s)
  def search_geofields
    %w(lat lng nx ny sx sy country state city suburb street postcode)
  end

  def search_availability_date(date)
    date ? date.strftime('%b %e') : ''
  end

  def search_availability_quantity
    params[:availability].present? && params[:availability][:quantity].to_i || 1
  end

  def search_amenities
    params[:amenities].present? && params[:amenities].map(&:to_i) || []
  end

  def search_price_min
    (params[:price].present? && params[:price][:min]) || 0
  end

  def search_price_max
    params[:price].present? && params[:price][:max] || PriceRange::MAX_SEARCHABLE_PRICE
  end

  def price_information(listing)
    if listing.hourly_reservations? && !listing.hourly_price.to_f.zero?
      "From #{money_without_cents_and_with_symbol(listing.hourly_price)} / hour"
    elsif !listing.daily_price.to_f.zero?
      "From #{money_without_cents_and_with_symbol(listing.daily_price)} / day"
    elsif !listing.weekly_price.to_f.zero?
      "From #{money_without_cents_and_with_symbol(listing.weekly_price)} / week"
    elsif !listing.monthly_price.to_f.zero?
      "From #{money_without_cents_and_with_symbol(listing.monthly_price)} / month"
    end
  end

end

app/views/search/_bar.html.haml
%form#listing_search.search_results{:action => search_path, :method => "get"}
  - search_geofields.each do |geofield|
    = hidden_field_tag geofield, ''
  = hidden_field_tag 'ignore_search_event', 0

  .row-fluid
    .span6
      %input#search{:name => "q", :placeholder => "Search by location", :type => "text", :value => query, :class => "query", :autocomplete => "off"}
      .geolocation
        %span.ico-crosshairs
    .span6
      .three.columns.availability-date-start
        = text_field_tag "availability[dates][start]", search_availability_dates_start, :autocomplete => "off", :placeholder => "Starting on"
        .calendar
          %span.ico-calender
      .three.columns.availability-date-end
        = text_field_tag "availability[dates][end]", search_availability_dates_end, :autocomplete => "off", :placeholder => "Ending on"
        .calendar
          %span.ico-calender

app/views/search/_filter.html.haml
.search-filter
  = link_to '#', :class => header_name.underscore.tr(" ","_"),  :'data-search-filter' => true  do
    %h3 
      %span.ico-chevron-down
      = header_name
  %ul
    - options.each do |option|
      %li
        %label.checkbox.small-checkbox
          %input{:type => 'checkbox', :name => input_name, :value => option[0], :checked => selected_values.include?(option[0].to_s)}
          #{option[1]}

app/views/search/_header.html.haml
- content_for :hero do
  %header#listing_search.container-fluid  
    .header-inner
      %form.search_results{:action => search_path(v: result_view), :method => "get"}
        - search_geofields.each do |geofield|
          = hidden_field_tag geofield, ''
        = hidden_field_tag :v, result_view
        = hidden_field_tag :ignore_search_event, 0
        = hidden_field_tag :page, 1
        .row-fluid
          .span12
            .list-map-toggle
              %a.map{ href: search_path(params.merge(v: 'map')), class: result_view == 'map' ? 'active' : nil, title: 'Map' }
                Map
              %a.list{ href: search_path(params.merge(v: 'list')), class: result_view == 'list' ? 'active' : nil, title: 'List' }
                List
            .search-container 
              %input#search{:name => "q", :placeholder => "Search by city or address", :type => "text", :value => query, :class => "query", :autocomplete => "off"}
              .geolocation
                %span.ico-crosshairs
            .search-icon.btn.btn-green
              %span.ico-search
            .search-filters{:'data-search-filters-container' => true}
              = render :partial => 'search/filter', :locals => { :header_name => 'Location Types', :selected_values => params[:location_types_ids] || [], :input_name => 'location_types_ids[]', :options => LocationType.all.map { |lt| [lt.id, lt.name] } }
              = render :partial => 'search/filter', :locals => { :header_name => 'Desk Types', :selected_values => params[:listing_types_ids] || [], :input_name => 'listing_types_ids[]', :options => ListingType.all.map { |lt| [lt.id, lt.name] } }
              = render :partial => 'search/filter', :locals => { :header_name => 'Industries', :selected_values => params[:industries_ids] || [], :input_name => 'industries_ids[]', :options => Industry.all.map { |i| [i.id, i.name] } }

app/views/search/index.html.haml
- legacy false
- title params[:q] if params[:q]
- content_for :hero do
  .container-fluid
    = render :partial => "search/bar", :locals => { :value => "" }

#results
  .google-map-wrapper
    .google-map
      #listings_map.inner{:tabindex => -1}

  .results
    = render :partial => "search/listings" if @listings

  .loading.four.columns{:style => "display: none"}
    = image_tag "spinner-red.gif"

- content_for :domready do
  new Search.SearchController($('#listing_search'), $("#results"))

app/views/search/list.html.haml
- legacy false
- no_footer!
- content_for :hero do
  = render 'search/header'

- if listings.any?
  %section#results.list
    = render partial: 'search/list/listing', collection: listings
    = will_paginate listings
    = render 'shared/loading_spinner'
- elsif !@located
  %section#results.no_results
    = render 'shared/loading_spinner'
    .text-center
      %br/
      %br/
      %h1.tk-adelle.fat No results found
      %p= t '.address_could_not_be_found'
- else
  %section#results.no_results
    = render 'shared/loading_spinner'
    .text-center
      %br/
      %br/
      %h1.tk-adelle.fat No results found
      #search-notification
        = render 'search_notifications/form', search_notification: search_notification
- content_for :domready do
  new Search.SearchController($('#listing_search form'), $("section#content.search"));

app/views/search/map.html.haml
- legacy false
- no_footer!
- content_for :hero do
  = render 'search/header'
  %section#map.google-map-wrapper
    .google-map
      #listings_map.inner

= render 'shared/loading_spinner'
- if listings.any?
  %section#results.map
    = render partial: 'search/map/marker', collection: listings, as: :listing
- elsif !@located
  %section#results.no_results
    = render 'shared/loading_spinner'
    .text-center
      %br/
      %br/
      %h1.tk-adelle.fat Searching...
- else
  %section#results.no_results
    .text-center
      %br/
      %br/
      %h1.tk-adelle.fat No results found
      %p Try a different location or a post code. Make sure the location is properly formatted and include the city and state.
      %p
        Still cant find what your looking for? Why not #{link_to "create your own #{platform_context.bookable_noun}", new_space_wizard_path}!

- content_for :domready do
  new Search.SearchController($('#listing_search form'), $("section#content.search"))

app/views/search/results.html.erb
<section class="grid_12 alpha omega list">

  <% if @search.blank? %>
    <p>Please enter a city or address</p>
  <% else %>

    <% if @workplaces.empty? %>
    <br />
      <div class="grid_3 alpha prefix_2">
        <%= image_tag "marker_missing.png" %>
      </div>
      <div class="grid_6 omega">
        <br /><br />
        <h1 class="tk-adelle fat">No results found</h1>
        <p>Try a different location or a post code. Make sure the location is properly formatted and include the city and state.</p>
        <p>Still cant find what your looking for? Why not <%= link_to "create your own workplace", new_workplace_path %>!</p>
      </div>
    <% else %>
      <div class="google-map">
        <div id="workplaces_map" class="inner" style="height: 350px;"></div>
      </div>

      <p><strong><%= pluralize(@workplaces.length, "workplace") %> found</strong>. Hover over a day to see how many desks are available.</p>

      <%= will_paginate @workplaces %>

      <% @workplaces.each do |workplace| %>
        <%= render :partial => '/workplaces/workplace.html', :locals => { :workplace => workplace } %>
      <% end %>

      <%= will_paginate @workplaces %>

      <script type="text/javascript">

        $(document).ready(function() {

          var map = new google.maps.Map(document.getElementById("workplaces_map"), {
            zoom: 8,
            mapTypeId: google.maps.MapTypeId.ROADMAP,
            mapTypeControl: false
          });

          var bounds = new google.maps.LatLngBounds();
          var markers = {}, infos = {};
          <% @workplaces.each do |w| %>
            ll = new google.maps.LatLng(<%= w.latitude %>, <%= w.longitude %>);
            bounds.extend(ll);
            markers[<%= w.id %>] = new google.maps.Marker({
              position: ll,
              map: map,
              icon: "<%= image_path("marker.png") %>",
              title: "<%= w.name %>"
            });
            infos[<%= w.id %>] = new google.maps.InfoWindow({
              content: "<%= escape_javascript(render(:partial => 'workplaces/gmap', :locals => { :workplace => w })) %>"
            });
            google.maps.event.addListener(markers[<%= w.id %>], 'click', function() {
              infos[<%= w.id %>].open(map, markers[<%= w.id %>]);
            });
          <% end %>
          map.fitBounds(bounds);

        });

      </script>
      <% end %>

  <% end %>

</section>