config/routes.rb
DesksnearMe::Application.routes.draw do

  if defined? MailView
    mount ReservationMailerPreview => 'mail_view/reservations'
    mount UserMailerPreview => 'mail_view/users'
    mount PostActionMailerPreview => 'mail_view/post_action'
    mount InquiryMailerPreview => 'mail_view/inquiries'
    mount ListingMailerPreview => 'mail_view/listings'
    mount RatingMailerPreview => 'mail_view/ratings'
    mount ListingMessagingMailerPreview => 'mail_view/listing_messaging'
    mount ReengagementMailerPreview => 'mail_view/reengagement'
    mount RecurringMailerPreview => 'mail_view/recurring'
  end

  match '/404', :to => 'errors#not_found'
  match '/422', :to => 'errors#server_error'
  match '/500', :to => 'errors#server_error'
  match '/domain-not-configured', :to => 'errors#domain_not_configured', :as => 'domain_not_configured'

  namespace :admin do
    match '/', :to => "dashboard#show"
    resources :users do
      member do
        post :login_as
      end

      collection do
        post :restore_session
      end
    end

    resources :reservations
    resources :companies
    resources :payment_transfers do
      member do
        post :transferred
      end

      collection do
        post :generate
      end
    end

    resources :instances do
      resources :partners
    end
    resources :pages
  end

  namespace :instance_admin do
    match '/', :to => "base#index"
    resources :analytics, :only => [:index]
    resources :inventories, :only => [:index, :show] do
      post :login_as, on: :member
      post :restore_session, on: :collection
    end
    resources :partners
    resources :settings, :only => [:index]
    resource :theme, :only => [:show, :update], :controller => 'theme'
    resources :transfers do
      member do
        post :transferred
      end

      collection do
        post :generate
      end
    end
    resources :users, :only => [:index, :create]
    resources :pages

    namespace :users do
      resources :instance_admins, :only => [:create, :update, :destroy, :index]
      resources :instance_admin_roles, :only => [:create, :update, :destroy, :index]
    end
  end

  resources :locations, :only => [:show] do
    resources :listings, :controller => 'locations/listings' do
      member do
        get :ask_a_question
      end
    end

    resource :social_share, :only => [:new], :controller => 'locations/social_share'

    collection do
      get :populate_address_components_form
      post :populate_address_components
    end
  end

  resources :listings, :only => [:index, :show] do
    resources :reservations, :only => [:create, :update], :controller => "listings/reservations" do
      collection do
        post :review
        post :store_reservation_request
      end
      member do
        get :booking_successful
      end
      get :hourly_availability_schedule, :on => :collection
    end

    resources :listing_messages, :controller => "listings/listing_messages" do
      put :archive
    end
  end

  resources :listing_messages, only: [:index] do 
    collection do 
      get :archived
    end
  end

  resources :reservations, :only => [] do
    resources :guest_ratings, :only => [:new, :create]
    resources :host_ratings, :only => [:new, :create]
  end
  match '/reservations/:id/guest_rating' => 'dashboard#guest_rating', as: 'guest_rating'
  match '/reservations/:id/host_rating' => 'reservations#host_rating', as: 'host_rating'

  match '/auth/:provider/callback' => 'authentications#create'
  match "/auth/failure", to: "authentications#failure"
  devise_for :users, :controllers => { :registrations => 'registrations', :sessions => 'sessions', :passwords => 'passwords' }
  devise_scope :user do
    post "users/avatar", :to => "registrations#avatar", :as => "avatar"
    get "users/edit_avatar", :to => "registrations#edit_avatar", :as => "edit_avatar"
    put "users/update_avatar", :to => "registrations#update_avatar", :as => "update_avatar"
    get "users/set_password", :to => "registrations#set_password", :as => "set_password"
    put "users/update_password", :to => "registrations#update_password", :as => "update_password"
    post "users/store_google_analytics_id", :to => "registrations#store_google_analytics_id", :as => "store_google_analytics"
    post "users/store_geolocated_location", :to => "registrations#store_geolocated_location", :as => "store_geolocated_location"
    get "users/", :to => "registrations#new"
    get "users/verify/:id/:token", :to => "registrations#verify", :as => "verify_user"
    delete "users/avatar", :to => "registrations#destroy_avatar", :as => "destroy_avatar"
    get "users/:id", :to => "registrations#show", :as => "profile"
    get "users/unsubscribe/:signature", :to => "registrations#unsubscribe", :as => "unsubscribe"

    put "users/store_correct_ip", :to => "sessions#store_correct_ip", :as => "store_correct_ip"
  end

  resources :reservations, :except => [:update, :destroy, :show] do
    member do
      post :user_cancel
      get :export
      get :booking_successful
    end
    collection do
      get :upcoming
      get :archived
    end
  end

  resource :dashboard, :only => [:show], :controller => 'dashboard' do
    member do
      get :bookings, :to => 'reservations#upcoming'
      get :analytics
      get :listings
      get :manage_guests
      get :transfers
    end
  end

  namespace :manage do

    resources :companies, :only => [:edit, :update, :show]

    resources :white_labels, :only => [:edit, :update, :show]

    resources :users, :except => [:edit, :update]
    resources :themes, :only => [] do
      member do
        delete :destroy_image
      end
    end

    resources :locations do
      resources :listings do
        member do
          get :enable
          get :disable
        end
      end
    end

    resources :photos, :only => [:create, :destroy, :edit, :update]

    resources :listings do
      resources :reservations, :controller => 'listings/reservations' do
        member do
          post :confirm
          get :confirm
          put :reject
          get :rejection_form
          post :host_cancel
        end
      end
    end
  end

  match "/search", :to => "search#index", :as => :search
  match "/search/show/:id", :to => "search#show"

  resources :search_notifications, only: [:create]

  resource :event_tracker, only: [:create], :controller => 'event_tracker'

  resources :authentications, :only => [:create, :destroy] do
    collection do
      post :clear # Clear authentications stored in session
    end
  end

  scope '/space' do
    get '/new' => 'space_wizard#new', :as => "new_space_wizard"
    get "/list" => "space_wizard#list", :as => "space_wizard_list"
    post "/list" => "space_wizard#submit_listing"
    put "/list" => "space_wizard#submit_listing"
    post "/photo" => "space_wizard#submit_photo", :as => "space_wizard_photo"
    put "/photo" => "space_wizard#submit_photo", :as => "space_wizard_photo"
    delete "/photo/:id" => "space_wizard#destroy_photo", :as => "destroy_space_wizard_photo"
  end

  root :to => "public#index"

  namespace :v1, :defaults => { :format => 'json' } do

    resource :authentication, only: [:create]
    post 'authentication/:provider', :to => 'authentications#social'

    resource :registration, only: [:create]

    get  'profile',  :to => 'profile#show'
    put  'profile',  :to => 'profile#update'
    post 'profile/avatar/:filename', :to => 'profile#upload_avatar'
    delete 'profile/avatar', :to => 'profile#destroy_avatar'

    get  'iplookup',  :to => 'iplookup#index'

    resources :guest_ratings, :only => [:create]
    resources :host_ratings, :only => [:create]

    resources :locations do
      collection do
        get 'list'
      end
    end

    resources :photos

    resources :listings, :only => [:show,:create, :update, :destroy] do
      member do
        post 'reservation'
        post 'availability'
        post 'inquiry'
        post 'share'
        get  'patrons'
        get  'connections'
      end
      collection do
        post 'search'
        post 'query'
      end
      resource :rating, only: [:show, :update, :destroy]
    end

    resources :reservations do
      collection do
        get 'past'
        get 'future'
      end
    end

    resource :social, only: [:show], controller: 'social' do
      # Hmm, can this be better?
      resource :facebook, only: [:show, :update, :destroy],
        controller: 'social_provider', provider: 'facebook'
      resource :twitter,  only: [:show, :update, :destroy],
        controller: 'social_provider', provider: 'twitter'
      resource :linkedin, only: [:show, :update, :destroy],
        controller: 'social_provider', provider: 'linkedin'
    end

    get 'amenities', to: 'amenities#index'
    get 'organizations', to: 'organizations#index'
  end

  match "/pages/:path", to: 'pages#show', as: :pages
  match "/w-hotels-desks-near-me", to: 'locations#w_hotels', as: :w_hotels_location
  match "/W-hotels-desks-near-me", to: 'locations#w_hotels'
  match "/careers", to: 'pages#careers'
  match "/rent-accounting-desks", to: 'locations#vertical_accounting'
  match "/rent-legal-desks", to: 'locations#vertical_law'
  match "/rent-hairdressing-booth-stations", to: redirect(subdomain: 'rent-salon-space', path: '/')
  match "/rent-design-desks", to: 'locations#vertical_design'
end

app/models/listing/search/area.rb
class Listing::Search::Area < Struct.new(:center, :bounds, :radius, :address_components)
  delegate :distance_from, :radians, to: :center

  def fetch_address_component(name)
    address_components.fetch_address_component(name)
  end
end

app/controllers/listings/listing_messages_controller.rb
class Listings::ListingMessagesController < ApplicationController

  before_filter :find_listing
  before_filter :redirect_to_login, only: [:new]
  before_filter :authenticate_user!, except: [:new]

  def new
    @listing_message = @listing.listing_messages.new
    setup_listing_message
  end

  def create
    @listing_message = @listing.listing_messages.new(params[:listing_message])
    setup_listing_message
    if @listing_message.save
      @listing_message.send_notification(platform_context)
      flash[:notice] = t('flash_messages.listing_messages.message_sent')
      redirect_to listing_messages_path
      render_redirect_url_as_json if request.xhr?
    else
      if request.xhr?
        render :template => 'listings/listing_messages/new'
      else
        @listing_messages = ListingMessage.for_thread(@listing, @listing_message).by_created.decorate
        render :show
      end
    end
  end

  def show
    @show_listing_message = @listing.listing_messages.find(params[:id])
    @listing_message = @listing.listing_messages.new(replying_to_id: @show_listing_message.id)

    @listing_messages = ListingMessage.for_thread(@listing, @show_listing_message).by_created.decorate

    to_mark_as_read = @listing_messages.select{|m| m.unread_for?(current_user)}
    ListingMessage.update_all({read: true},
                              {id: to_mark_as_read.map(&:id)})

    event_tracker.track_event_within_email(current_user, request) if params[:track_email_event]
  end

  def archive
    @listing_message = @listing.listing_messages.find(params[:listing_message_id])
    column = @listing_message.archived_column_for(current_user)
    ListingMessage.update_all({column => true},
                              {owner_id: @listing_message.owner_id, listing_id: @listing.id})
    flash[:notice] = t('flash_messages.listing_messages.message_archived')
    redirect_to listing_messages_path
  end

  private

  def find_listing
    @listing = Listing.find(params[:listing_id])
  end

  def setup_listing_message
    @listing_message.author = current_user
    @listing_message.owner = if @listing_message.first_in_thread?
      current_user
    else
      @listing_message.previous_in_thread.owner
    end
    @listing_message.decorate
  end

  def redirect_to_login
    return if user_signed_in?
    session[:user_return_to] = ask_a_question_location_listing_url(@listing.location, @listing)
    redirect_to new_user_session_path
  end

end

app/controllers/listings/reservations_controller.rb
class Listings::ReservationsController < ApplicationController

  before_filter :find_listing
  before_filter :find_reservation, only: [:booking_successful]
  before_filter :build_reservation_request, :only => [:review, :create, :store_reservation_request]
  before_filter :require_login_for_reservation, :only => [:review, :create]
  before_filter :find_current_country, :only => [:review]

  def review
    event_tracker.reviewed_a_booking(@reservation_request.reservation)
  end

  def create
    @reservation = @reservation_request.reservation
    if @reservation_request.process
      if @reservation_request.confirm_reservations?

        @reservation.schedule_expiry(platform_context)
        ReservationMailer.enqueue.notify_host_with_confirmation(platform_context, @reservation)
        ReservationMailer.enqueue.notify_guest_with_confirmation(platform_context, @reservation)
        begin
          ReservationSmsNotifier.notify_host_with_confirmation(@reservation).deliver
        rescue Twilio::REST::RequestError => e
          if e.message.include?('is not a valid phone number')
            @reservation.host.notify_about_wrong_phone_number(platform_context)
          else
            BackgroundIssueLogger.log_issue("[internal] twilio error - #{e.message}", "support@desksnear.me", "Reservation id: #{@reservation.id}, guest #{current_user.name} (#{current_user.id}). #{$!.inspect}")
          end
        end
        event_tracker.updated_profile_information(@reservation.owner)
        event_tracker.updated_profile_information(@reservation.host)
      else
        ReservationMailer.enqueue.notify_host_without_confirmation(platform_context, @reservation)
        ReservationMailer.enqueue.notify_guest_of_confirmation(platform_context, @reservation)
      end

      pre_booking_sending_date = (@reservation.date - 1.day).to_time_in_current_zone + 17.hours # send day before at 5pm
      if pre_booking_sending_date < Time.current.beginning_of_day
        ReservationPreBookingJob.perform_later(pre_booking_sending_date, platform_context, @reservation)
      end

      if current_user.reservations.count == 1
        ReengagementOneBookingJob.perform_later(@reservation.last_date.to_time_in_current_zone + 7.days, platform_context, @reservation)
      end

      event_tracker.requested_a_booking(@reservation)
      card_message = @reservation.credit_card_payment? ? t('flash_messages.reservations.credit_card_will_be_charged') : ''
      flash[:notice] = t('flash_messages.reservations.reservation_made', message: card_message)
      redirect_to booking_successful_reservation_path(@reservation)
    else
      render :review
    end
  end

  # Renders booking successful modal
  def booking_successful
  end

  def hourly_availability_schedule
    schedule = if params[:date].present?
      date = Date.parse(params[:date])
      @listing.hourly_availability_schedule(date).as_json
    end

    render :json => schedule.presence || {}
  end

  # Store the reservation request in the session so that it can be restored when returning to the listings controller.
  def store_reservation_request
    session[:stored_reservation_location_id] = @listing.location.id

    # Marshals the booking request parameters into a better structured hash format for transmission and
    # future assignment to the Bookings JS controller.
    #
    # Returns a Hash of listing id's to hash of date & quantity values.
    #  { '123' => { 'date' => '2012-08-10', 'quantity => '1' }, ... }
    session[:stored_reservation_bookings] = {
      @listing.id => {
        :quantity => @reservation_request.reservation.quantity,
        :dates => @reservation_request.reservation.periods.map { |period| period.date.strftime('%Y-%m-%d') }
      }
    }
    head 200 if params[:action] == 'store_reservation_request'
  end

  private

  def require_login_for_reservation
    unless user_signed_in?
      store_reservation_request
      redirect_to new_user_registration_path(return_to: location_listing_url(@listing.location, @listing, restore_reservations: true))
    end
  end

  def find_listing
    @listing = Listing.find(params[:listing_id])
  end

  def find_reservation
    @reservation = @listing.reservations.find(params[:id])
  end

  def build_reservation_request
    attributes = params[:reservation_request] || {}

    @reservation_request = ReservationRequest.new(
      @listing,
      current_user,
      {
        :quantity       => attributes[:quantity],
        :dates          => attributes[:dates],
        :start_minute   => attributes[:start_minute],
        :end_minute     => attributes[:end_minute],
        :card_expires   => attributes[:card_expires],
        :card_code      => attributes[:card_code],
        :card_number    => attributes[:card_number],
        :country_name   => attributes[:country_name],
        :mobile_number  => attributes[:mobile_number]
      }
    )
  end
  
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_filter :redirect_if_invalid_page_param, :only => [:index]
  before_filter :find_listing, :only => [:show]

  def index
    @listings = Listing.latest.merge(search_scope).paginate(:page => params[:page])
  end

  def show
    redirect_to location_listing_path(@location, @listing)
  end

  protected

  def redirect_if_invalid_page_param
    unless params[:page] && params[:page].match(/^[0-9]*[1-9][0-9]*$/)
      redirect_to listings_path(:page =>1), :flash => { :warning => "Requested page does not exist, showing first page." }
    end
  end

  def find_listing
    @listing = Listing.with_deleted.find(params[:id])
    @location = @listing.location
  end

end

app/views/locations/listings/_administrator.html.haml
.padding-row
.administrator
  = image_tag administrator.avatar.url(:big)
  .info
    %span.name= administrator.name
    %span.title= administrator.job_title
  .buttons
    = link_to profile_path(administrator), :class => 'btn btn-gray-dark btn-medium view' do
      %span.text View profile
    = link_to new_listing_listing_message_path(@listing), :class => "btn btn-blue btn-medium ask", :rel => "modal" do
      %span.text Contact host
  .clearfix

app/views/locations/listings/_availabilities.html.haml
.padding-row
.availabilities
  = pretty_availability_sentence(listing.availability)

app/views/locations/listings/_booking.html.haml
%article.booking
  .listings
    .listing{listing_data_attributes(listing)}
      = render 'locations/booking_module', listing: listing

app/views/locations/listings/_company.html.haml
%article.company
  %h2
    = location.company.name
    - if location.company.url.present?
      = link_to location.company.url, target: '_blank' do
        %span.ico-open-link

  %p= location.company.description
  - if location.company.industries.any?
    .amenities-block
      .amenities-header
        %h3 Industries
        %a{href: '#industries'}
          %h3 Industries
          %span.ico-chevron-right
      .amenities-container
        - location.company.industries.order('name ASC').in_groups_of(4).each do |industry_group|
          .row-fluid.amenities-row
            - industry_group.compact.each do |industry|
              .span3{title: industry.name}
                = industry.name
    .clearfix

app/views/locations/listings/_listing_photos.html.haml
%article.photos
  = render :layout => 'locations/listings/photos_gallery', :locals =>  {:listing => listing, :gallery_id => 'photos-container', :photo_size => :golden, :fullscreen => false} do
    %button.enlarge.btn{:type => "button", :'data-gallery-enlarge' => true, :'data-toggle' => "modal", :'data-target' => "#fullscreen-gallery"}
      %span.ico-enlarge


#fullscreen-gallery.modal.hide.fade.modal-fullscreen{"aria-hidden" => "true", "aria-labelledby" => "fullscreen-gallery-label", :role => "dialog", :tabindex => "-1"}
  .loading
    = image_tag 'components/modal/loader.gif'

  #fullscreen-gallery-content.modal-body
    = render :layout => 'locations/listings/photos_gallery', :locals =>  {:listing => listing, :gallery_id => 'photos-container-enlarged', :photo_size => :large, :fullscreen => true} do
      %button.btn.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"}
        %span.ico-close

app/views/locations/listings/_location.html.haml
%article.location
  %h2
    The location
    - if current_user.try(:admin)
      = link_to login_as_admin_user_path(location.creator, :return_to => edit_manage_location_path(location)), :method => :post, :confirm => "This will log you out and re-log you in as location creator" do
        %span.ico-edit
  %p= location.description
  - if location.amenities.any?
    .amenities-block
      .amenities-header
        %h3 Amenities
        %a{href: '#amenities'}
          %h3 Amenities
          %span.ico-chevron-right
      .amenities-container
        - location.amenities.order('name ASC').in_groups_of(4).each do |amenity_group|
          .row-fluid.amenities-row
            - amenity_group.compact.each do |amenity|
              .span3{title: amenity.name}
                = amenity.name
    .clearfix

app/views/locations/listings/_other_listings.html.haml
- if (selected_listing_siblings(location, listing)).count > 0 
  .padding-row
  .other-listings
    %header
      %h3 Other listings at this location
      %p{:'data-sibling-listing-name' => selected_listing_siblings(location, listing).first.name}
        = link_to selected_listing_siblings(location, listing).first.name, location_listing_path(location, selected_listing_siblings(location, listing).first)
    .listing-photos
      #listing-siblings-container.carousel.slide
        %ol.carousel-indicators
          - selected_listing_siblings(location, listing).each_with_index do |listing, index|
            %li{:class => index.zero? ? "active" : '', :'data-target' => '#listing-siblings-container', :'data-slide-to' => index}= index+1
        .carousel-inner
          - selected_listing_siblings(location, listing).each_with_index do |listing, index|
            - if photo = listing.photos.first
              .item{:class => ("active" if index == 0), :data => {:'listing-name' => listing.name, :'listing-url' => location_listing_path(listing.location, listing)}}
                = link_to location_listing_path(listing.location, listing) do 
                  = image_tag photo.image_url(:golden), :alt => photo.content.name
                .info
                  .caption
                    = render :partial => 'search/shared/price_information', :locals => { :listing => listing }
            - else
              .item{:class => ("active")}
                = image_tag space_listing_placeholder_path(:height => 554, :width => 895), :title => listing.name, :alt => listing.name
        - if selected_listing_siblings(location, listing).size > 1
          .carousel-nav
            = link_to "", "#listing-siblings-container", :class => "carousel-control left ico-chevron-left", 'data-slide' => 'prev'
            = link_to "", "#listing-siblings-container", :class => "carousel-control right ico-chevron-right", 'data-slide' => 'next'

app/views/locations/listings/_photos_gallery.html.haml
.listing-photos{:'data-photo-aspect-w' => PhotoUploader::SPACE_FULL_IMAGE_W, :'data-photo-aspect-h' => PhotoUploader::SPACE_FULL_IMAGE_H}
  .carousel{id: gallery_id, class: fullscreen ? '' : 'slide'}
    - if listing.photos.any?
      %ol.carousel-indicators
        - listing.photos.each_with_index do |photo, index|
          %li{:class => index.zero? ? "active" : '', :'data-target' => "##{gallery_id}", :'data-slide-to' => index}
            = index+1
      .carousel-inner
        - listing.photos.each_with_index do |photo, index|
          .item{:class => ("active" if index == 0), :'data-modalize' => true}
            - if fullscreen
              %img{:alt => photo.content.name, :'data-src' => photo.image_url(photo_size)}
            - else
              = image_tag photo.image_url(photo_size), :alt => photo.content.name
            .info
              - if photo.caption.present?
                .caption
                  = photo.caption
      = yield

    - else
      .carousel-inner
        .item{:class => ("active")}
          = image_tag space_listing_placeholder_path(:height => 554, :width => 895), :title => listing.name, :alt => listing.name

    - if listing.photos.size > 1
      .carousel-nav
        = link_to "", "##{gallery_id}", :class => "carousel-control left ico-chevron-left", 'data-slide' => 'prev'
        = link_to "", "##{gallery_id}", :class => "carousel-control right ico-chevron-right", 'data-slide' => 'next'

app/views/locations/listings/_show.html.haml
- title @listing.name_with_address

- content_for :hero do
  %article#space
    .container-fluid
      .row-fluid.padding-row
        .span12.nested
          %h1 #{@listing.name_with_address}

      .container-row
        .two-thirds.column.left
          = render 'locations/listings/listing_photos', listing: @listing 

          .padding-row
          %article.listing
            %h2
              = "The #{@listing.listing_type.name}"
              - if current_user.try(:admin)
                = link_to login_as_admin_user_path(@location.creator, :return_to => edit_manage_listing_path(@listing)), :method => :post, :confirm => "This will log you out and re-log you in as listing creator" do
                  %span.ico-edit
            %p= @listing.description

          = render 'locations/listings/location', location: @location 

          = render 'locations/listings/company', location: @location

        .one-third.column.left
          = render 'locations/listings/booking', listing: @listing

          .padding-row
          = render 'locations/listings/social_buttons', listing: @listing

          .padding-row
          = render 'locations/google_map', location: @location 

          = render 'locations/listings/availabilities', listing: @listing

          = render 'locations/listings/administrator', administrator: @listing.administrator

          = render 'locations/listings/other_listings', location: @location, listing: @listing


.clearfix.padding-row


- content_for :script do
  :javascript
    // Initialize the ui controller
    $(function() {
      new Space.Controller(
        $('article#space'),
        {
          bookings: {
            listings: #{raw location_listings_json},

            // Have we returned from setting up a session. If there are bookings, the JS controller
            // will trigger showing the booking confirmation modal.
            returnedFromSession: #{@initial_bookings.present? ? 'true' : 'false'}
          }
        });
      });

- content_for :domready do
  - if params[:action] == 'ask_a_question'
    Modal.load('#{new_listing_listing_message_path(@listing)}')

app/views/locations/listings/_social_buttons.html.haml
- content_for :meta do
  = render :partial => 'shared/og_meta', :locals => { :listing => listing, :url => location_listing_url(listing.location, listing) }
.social-buttons-wrapper
  .facebook
    .fb-like{:'data-href' => location_listing_url(listing.location, listing), :'data-colorscheme' => "light", :'data-layout' => "button_count", :'data-action' => "like", :'data-show-faces' => "false", :'data-send' => "false"}
    #fb-root
    :javascript
      (function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) return;
      js = d.createElement(s); js.id = id;
      js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=#{Social::Facebook::KEY}";
      fjs.parentNode.insertBefore(js, fjs);
      }(document, 'script', 'facebook-jssdk'));

  .social-buttons

    .twitter
      = link_to "Tweet", "https://twitter.com/share", :class => "twitter-share-button", :'data-text' => listing.name, :'data-url' => location_listing_url(listing.location, listing)
      %script
        !function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');

    .linkedin
      %script{:src => "//platform.linkedin.com/in.js", :type => "text/javascript", :lang => 'en_US'}
      %script{:type => "IN/Share", :'data-counter' => "right", :'data-url' => location_listing_url(listing.location, listing)}

    .google-plus
      .g-plusone{:'data-size' => "medium", :'data-href' => location_listing_url(listing.location, listing)}
      :javascript
        window.___gcfg = {
          parsetags: 'onload'
        };
        (function() {
          var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
          po.src = 'https://apis.google.com/js/plusone.js';
          var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
          })();
  .clearfix

app/views/locations/listings/show.html.haml
- legacy false

= render 'locations/listings/show'